---
defaults:
  # Which registry to push built images to
  # (requires having already authenticated
  # as a user with push access)
  registry: docker.chameleoncloud.org
  # The base release of OpenStack to build from.
  # This determines which checkout of Kolla
  # to use, as well as the base requirements that
  # build the openstack-base images.
  # Defaults to the value of $OPENSTACK_RELEASE
  # for legacy reasons.
  openstack_release: train
  # The Docker tag to add to the built image(s).
  # Defaults to $DOCKER_TAG for legacy reasons.
  tag: train
  # See [profiles] in kolla-build.conf -- this determines
  # which images are built.
  # Defaults to the value of $KOLLA_BUILD_PROFILE
  # for legacy reasons.
  profile:
  # Kolla image defaults, shouldn't need to change
  # these any time soon.
  type: source
  namespace: kolla
  # EXTRA PARAMETERS
  # These are just used to template the *.j2 files for the kolla
  # build configuration
  build_conf_extras:
    enable_networking_wireguard: True

config_sets:
  aarch64_debian:
    base: debian
    base_tag: "10"
    base_arch: aarch64
    platform: linux/arm64
    tag: train-aarch64

  aarch64_ubuntu:
    base: ubuntu
    base_tag: "18.04"
    base_arch: aarch64
    platform: linux/arm64
    tag: train-aarch64 

  x86_centos:
    base: centos
    base_tag: "8"
    base_arch: x86_64
    platform: linux/amd64
  
  x86_ubuntu:
    base: ubuntu
    base_tag: "18.04"
    base_arch: x86_64
    platform: linux/amd64

  # LEGACY, remove after migration off Trian. 
  # Neutron must run at the same OS distribution as the host currently due
  # to the iptables/nf_tables migration, in particular b/w CentOS7 and 8.
  # CentOS 7 host kernel doesn't support nf_tables and the userland binaries
  # assume iptables.
  neutron_centos7:
    base_tag: "7"
    profile: neutron_centos7
    tag: train-centos7
    build_conf_extras:
      # networking-wireguard requires Python 3
      enable_networking_wireguard: False
