---
defaults:
  # Which registry to push built images to
  # (requires having already authenticated
  # as a user with push access)
  # registry: docker.chameleoncloud.org
  # The base release of OpenStack to build from.
  # This determines which checkout of Kolla
  # to use, as well as the base requirements that
  # build the openstack-base images.
  # Defaults to the value of $OPENSTACK_RELEASE
  # for legacy reasons.
  openstack_release: train
  # The Docker tag to add to the built image(s).
  # Defaults to $DOCKER_TAG for legacy reasons.
  tag: train
  # See [profiles] in kolla-build.conf -- this determines
  # which images are built.
  # Defaults to the value of $KOLLA_BUILD_PROFILE
  # for legacy reasons.
  profile:
  # Kolla image defaults, shouldn't need to change
  # these any time soon.
  base: centos
  base_tag: 8
  base_arch: x86_64
  type: source
  # namespace: kolla

config_sets:
  base:
    profile: base
  blazar:
    profile: blazar
  cinder:
    profile: cinder
  cyborg:
    profile: cyborg
  doni:
    profile: doni
  glance:
    profile: glance
  gnocchi:
    profile: gnocchi
  heat:
    profile: heat
  horizon:
    profile: horizon
  horizon_kvm:
    profile: horizon_kvm
  ironic:
    profile: ironic
  keystone:
    profile: keystone
  neutron:
    profile: neutron
  nova:
    profile: nova
  placement:
    profile: placement
  zun:
    profile: zun

  # Neutron must run at the same OS distribution as the host currently due
  # to the iptables/nf_tables migration, in particular b/w CentOS7 and 8.
  # CentOS 7 host kernel doesn't support nf_tables and the userland binaries
  # assume iptables.
  neutron_centos7:
    base_tag: "7"
    profile: neutron
    tag: train-centos7

  # build neutron quickly for centos8 patches
  neutron_centos8:
    base: centos
    base_tag: "8"
    profile: neutron

  # build neutron quickly for ubuntu support
  neutron_ubuntu:
    base: ubuntu
    base_tag: "18.04"
    profile: neutron

  # ARM64 configuration for edge deployments. Many edge devices (e.g.,
  # the Raspberry Pi platform) are ARM-based and cannot run x86 containers.
  # Debian is used as the base in this case, as it has the most support in
  # Kolla for ARM.
  edge_aarch64_debian:
    base: debian
    base_tag: "10"
    base_arch: aarch64
    profile: edge
    platform: linux/arm64
    tag: train-aarch64

  # Ubuntu for ARM64 edge deployments. This mostly exists because the
  # Jetson platform uses L4T, which is Ubuntu-based, and the Jetson kernel
  # is built with some assumptions based in Ubuntu 18.04, such as iptables
  # instead of nf_tables.
  edge_aarch64_ubuntu:
    base: ubuntu
    base_tag: "18.04"
    base_arch: aarch64
    profile: edge
    platform: linux/arm64
    tag: train-aarch64

  # We have some edge deployments that support x86; this builds just the
  # edge services for that architecture.
  edge_x86_centos:
    base: centos
    base_tag: "8"
    base_arch: x86_64
    profile: edge

  # We have some edge deployments that support x86; this builds just the
  # edge services for that architecture.
  edge_x86_ubuntu:
    base: ubuntu
    base_tag: "18.04"
    base_arch: x86_64
    profile: edge
