[DEFAULT]
maintainer = University of Chicago

registry = ghcr.io
namespace = chameleoncloud/kolla
openstack_release = 2024.1

base = ubuntu
base_tag = "24.04"
base_arch = x86_64
platform = linux/amd64

tag = 2024.1-ubuntu-noble

[profiles]
#profiles here correspond roughly to the tags used by kolla-ansible during deploy
blazar = ^blazar
doni = ^doni
glance = ^glance
heat = ^heat
horizon = ^horizon
ironic  = ^ironic(?!-neutron),dnsmasq
keystone = ^keystone
neutron  = ^neutron,ironic-neutron-agent,neutron-wireguard-agent
manila = ^manila-
nova    = ^nova
placement = ^placement
prometheus = ^prometheus
tunelo = ^tunelo
k3s = ^k3s
zun = ^zun
support = ^base,chrony,cron,fluentd,^haproxy,keepalived,^kolla-toolbox,^letsencrypt,^mariadb,memcached,^openstack-base,^openvswitch,rabbitmq

[blazar-base]
type = git
location = https://github.com/ChameleonCloud/blazar.git
reference = chameleoncloud/2023.1
# reference = wip/chameleoncloud/2024.1

[blazar-manager-additions-extra]
type = local
location = blazar/additions/blazar-manager


[doni-base]
type = git
location = https://github.com/ChameleonCloud/doni.git
reference = wip/chameleoncloud/2024.1

[tunelo-base]
type = git
location = https://github.com/ChameleonCloud/tunelo.git
reference = wip/chameleoncloud/2024.1

[heat-base]
type = git
location = https://github.com/ChameleonCloud/heat.git
reference = wip/chameleoncloud/2024.1

[horizon]
type = git
location = https://github.com/ChameleonCloud/horizon.git
reference = wip/chameleoncloud/2024.1

[horizon-plugin-blazar-dashboard]
type = git
location = https://github.com/ChameleonCloud/blazar-dashboard.git
reference = chameleoncloud/2023.1
# reference = wip/chameleoncloud/2024.1

[horizon-plugin-heat-dashboard]
type = git
location = https://github.com/ChameleonCloud/heat-dashboard.git
reference = wip/chameleoncloud/2024.1

[ironic-base]
type = git
location = https://github.com/ChameleonCloud/ironic.git
reference = wip/chameleoncloud/2024.1

[keystone-base]
type = git
location = https://github.com/ChameleonCloud/keystone.git
reference = wip/chameleoncloud/2024.1


[neutron-base-plugin-networking-generic-switch]
type = git
location = https://github.com/ChameleonCloud/networking-generic-switch.git
reference = wip/chameleoncloud/2024.1

[neutron-base-plugin-networking-wireguard]
type = git
location = https://github.com/ChameleonCloud/networking-wireguard.git
reference = wip/chameleoncloud/2024.1

[nova-base]
type = git
location = https://github.com/ChameleonCloud/nova.git
reference = wip/chameleoncloud/2024.1

[horizon-plugin-zun-ui]
type = git
location = https://github.com/ChameleonCloud/zun-ui.git
reference = wip/chameleoncloud/2024.1

[zun-base]
type = git
location = https://github.com/ChameleonCloud/zun.git
reference = wip/chameleoncloud/2024.1
