[DEFAULT]
maintainer = University of Chicago

# Defaults for all variants
registry = docker.chameleoncloud.org

# default build properties
base = ubuntu
base_arch = x86_64
platform = linux/amd64
openstack_release = xena

[profiles]

blazar = ^blazar-
cinder = ^cinder-
doni = ^doni-
glance = ^glance-
gnocchi = ^gnocchi-
heat = ^heat-
horizon = ^horizon$
ironic = ^ironic(?!-neutron),dnsmasq,iscsi
keystone = ^keystone
manila = ^manila-
neutron = ironic-neutron-agent,^neutron-(base|dhcp-agent|l3-agent|metadata-agent|openvswitch-agent|server|wireguard-agent)$,^ovn-
nova = ^nova-
placement = ^placement
tunelo = ^tunelo-
zun = ^zun-


# Forks
[blazar-base]
type = git
location = https://github.com/ChameleonCloud/blazar.git
reference = chameleoncloud/{{ openstack_release }}

[blazar-manager-additions-extra]
type = local
location = $locals_base/additions.tar

[cyborg-base]
type = git
location = https://github.com/ChameleonCloud/cyborg.git
reference = chameleoncloud/{{ openstack_release }}

# NOTE(jason): Gnocchi uses 4.3 as that's the closest to xena; consider updating
# when we move past xena on the base.
[gnocchi-base]
type = git
reference = stable/4.3
location = https://github.com/gnocchixyz/gnocchi.git

[heat-base]
type = git
location = https://github.com/ChameleonCloud/heat.git
reference = chameleoncloud/{{ openstack_release }}

[horizon-additions-theme-chameleoncloud]
type = git
location = https://github.com/ChameleonCloud/horizon-theme.git
reference = master

[horizon]
type = git
location = https://github.com/ChameleonCloud/horizon.git
reference = chameleoncloud/{{ openstack_release }}

[horizon-plugin-blazar-dashboard]
type = git
location = https://github.com/ChameleonCloud/blazar-dashboard.git
reference = chameleoncloud/{{ openstack_release }}

[horizon-plugin-heat-dashboard]
type = git
location = https://github.com/ChameleonCloud/heat-dashboard.git
reference = chameleoncloud/{{ openstack_release }}

[horizon-plugin-zun-ui]
type = git
location = https://github.com/ChameleonCloud/zun-ui.git
reference = stable/{{ openstack_release }}

[ironic-base]
type = git
location = https://github.com/ChameleonCloud/ironic.git
reference = chameleoncloud/{{ openstack_release }}

[keystone-base]
type = git
location = https://github.com/ChameleonCloud/keystone.git
reference = chameleoncloud/{{ openstack_release }}

[neutron-base]
type = git
location = https://github.com/ChameleonCloud/neutron.git
reference = chameleoncloud/{{ openstack_release }}

[neutron-base-plugin-networking-generic-switch]
type = git
location = https://github.com/ChameleonCloud/networking-generic-switch.git
reference = chameleoncloud/{{ openstack_release }}

[neutron-base-plugin-networking-wireguard]
type = git
location = https://github.com/ChameleonCloud/networking-wireguard.git
reference = chameleoncloud/{{ openstack_release }}

[neutron-server-additions-extra]
type = local
location = $locals_base/additions.tar

[nova-base]
type = git
location = https://github.com/ChameleonCloud/nova.git
reference = chameleoncloud/{{ openstack_release }}

[nova-base-plugin-blazar]
type = git
location = https://github.com/ChameleonCloud/blazar-nova.git
reference = chameleoncloud/{{ openstack_release }}

[zun-base]
type = git
location = https://github.com/ChameleonCloud/zun.git
reference = chameleoncloud/{{ openstack_release }}


# New Services

[doni-base]
type = git
location = https://github.com/ChameleonCloud/doni.git
reference = chameleoncloud/xena

[tunelo-base]
type = git
location = https://github.com/ChameleonCloud/tunelo.git
reference = chameleoncloud/{{ openstack_release }}
