[DEFAULT]
maintainer = University of Chicago

registry = ghcr.io
namespace = chameleoncloud/kolla
openstack_release = 2023.1

base = ubuntu
base_tag = "22.04"
base_arch = x86_64
platform = linux/amd64

tag = 2023.1-ubuntu-jammy

[profiles]
#profiles here correspond roughly to the tags used by kolla-ansible during deploy
blazar = ^blazar
doni = ^doni
glance = ^glance
heat = ^heat
horizon = ^horizon
ironic  = ^ironic(?!-neutron),dnsmasq
keystone = ^keystone
neutron  = ^neutron,ironic-neutron-agent,neutron-wireguard-agent
manila = ^manila-
nova    = ^nova
placement = ^placement
prometheus = ^prometheus
tunelo = ^tunelo

[blazar-base]
type = git
location = https://github.com/ChameleonCloud/blazar.git
reference = chameleoncloud/2023.1

[blazar-manager-additions-extra]
type = local
location = blazar/additions/blazar-manager


[doni-base]
type = git
location = https://github.com/ChameleonCloud/doni.git
reference = chameleoncloud/2023.1

[tunelo-base]
type = git
location = https://github.com/ChameleonCloud/tunelo.git
reference = chameleoncloud/2023.1

[heat-base]
type = git
location = https://github.com/ChameleonCloud/heat.git
reference = chameleoncloud/2023.1

[horizon]
type = git
location = https://github.com/ChameleonCloud/horizon.git
reference = chameleoncloud/2023.1

[horizon-plugin-blazar-dashboard]
type = git
location = https://github.com/ChameleonCloud/blazar-dashboard.git
reference = chameleoncloud/2023.1

[horizon-plugin-heat-dashboard]
type = git
location = https://github.com/ChameleonCloud/heat-dashboard.git
reference = chameleoncloud/2023.1

[ironic-base]
type = git
location = https://github.com/ChameleonCloud/ironic.git
reference = chameleoncloud/2023.1

[keystone-base]
type = git
location = https://github.com/ChameleonCloud/keystone.git
reference = chameleoncloud/2023.1


[neutron-base-plugin-networking-generic-switch]
type = git
location = https://github.com/ChameleonCloud/networking-generic-switch.git
reference = chameleoncloud/2023.1

[neutron-base-plugin-networking-wireguard]
type = git
location = https://github.com/ChameleonCloud/networking-wireguard.git
reference = chameleoncloud/2023.1

[nova-base]
type = git
location = https://github.com/ChameleonCloud/nova.git
reference = chameleoncloud/2023.1
