pipeline {
  agent any

  parameters {
    string(name: 'HEAT_JOB_NAME', defaultValue: 'heat/chameleoncloud%2Fstable%2Frocky',
           description: 'Jenkins job name for heat')
  }

  triggers {
    upstream(upstreamProjects: "base-kolla/${env.BRANCH_NAME},${params.HEAT_JOB_NAME}", threshold: hudson.model.Result.SUCCESS)

    GenericTrigger(
      genericVariables: [
        [key: 'ref', value: '$.ref'],
        [key: 'changed_files', value: '$.commits[*].["modified","added","removed"][*]']
      ],
      causeString: 'Triggered on $ref',
      token: JOB_NAME,
      printContributedVariables: true,
      regexpFilterText: '$ref $changed_files',
      regexpFilterExpression: 'refs/heads/master .*heat/'
    )
  }

  environment {
    // Necessary so that `docker login` credentials are not put in shared location
    HOME = "${env.WORKSPACE}"
    DOCKER_REGISTRY = 'docker.chameleoncloud.org'
    DOCKER_REGISTRY_CREDS = credentials('kolla-docker-registry-creds')
  }

  stages {
    stage('docker-setup') {
      steps {
        sh 'docker login --username=$DOCKER_REGISTRY_CREDS_USR --password=$DOCKER_REGISTRY_CREDS_PSW $DOCKER_REGISTRY'
      }
    }

    stage('build-and-publish') {
      environment {
        KOLLA_BUILD_PROFILE = 'heat'
        KOLLA_PUSH = 'yes'
      }

      steps {
        copyArtifacts(projectName: "${params.HEAT_JOB_NAME}",
                      target: "${env.WORKSPACE}/sources")
        sh "make clean"
        sh "make build-with-locals"
      }
    }
  }

  post {
    always {
      sh 'docker logout $DOCKER_REGISTRY'
    }

    success {
      build job: 'kolla-ansible-deploy', wait: false, parameters: [
        string(name: 'KOLLA_SERVICE_NAME', value: 'heat'),
        string(name: 'JENKINS_AGENT_LABEL', value: 'ansible-uc-dev')
      ]
    }
  }
}
