pipeline {
  agent any

  parameters {
    string(name: 'NETWORKING_GENERIC_SWITCH_JOB_NAME', defaultValue: '/networking-generic-switch/chameleoncloud%2Ftrain',
           description: 'Jenkins job name for networking-generic-switch dependency')
    string(name: 'DOCKER_TAG', defaultValue: 'train-centos7',
           description: 'Tag to apply to built docker image')
  }

  triggers {
    upstream(upstreamProjects: "/base-kolla/${env.BRANCH_NAME},${params.NETWORKING_GENERIC_SWITCH_JOB_NAME}",
             threshold: hudson.model.Result.SUCCESS)
  }

  environment {
    // Necessary so that `docker login` credentials are not put in shared location
    HOME = "${env.WORKSPACE}"
    DOCKER_REGISTRY = 'docker.chameleoncloud.org'
    DOCKER_REGISTRY_CREDS = credentials('kolla-docker-registry-creds')
  }

  stages {
    stage('docker-setup') {
      steps {
        sh 'docker login --username=$DOCKER_REGISTRY_CREDS_USR --password=$DOCKER_REGISTRY_CREDS_PSW $DOCKER_REGISTRY'
      }
    }

    stage('build-and-publish') {
      environment {
        KOLLA_BUILD_PROFILE = 'neutron'
        KOLLA_PUSH = 'yes'
        // Force to build entire chain
        KOLLA_USE_CACHE = 'no'
      }

      steps {
        copyArtifacts(projectName: "${params.NETWORKING_GENERIC_SWITCH_JOB_NAME}",
                      target: "${env.WORKSPACE}/sources")
        sh 'rm -rf build'
        withPythonEnv('python3') {
          sh './run.sh python build.py --push --use-cache'
        }
      }
    }
  }

  post {
    always {
      sh 'docker logout $DOCKER_REGISTRY'
    }

    failure {
      slackSend(
        channel: "#notifications",
        message: "*Build* of *neutron* (${env.DOCKER_TAG}) failed. <${env.RUN_DISPLAY_URL}|View build log>",
        color: "danger"
      )
    }

    success {
      slackSend(
        channel: "#notifications",
        message: "*Build* of *neutron* (${env.DOCKER_TAG}) completed successfuly. <${env.RUN_DISPLAY_URL}|View build log>",
        color: "good"
      )
      build job: 'kolla-ansible-deploy', wait: false, parameters: [
        string(name: 'KOLLA_SERVICE_NAME', value: 'neutron'),
        string(name: 'JENKINS_AGENT_LABEL', value: 'ansible-uc-dev')
      ]
    }
  }
}
