pipeline {
  agent any

  parameters{
    string(name: 'DOCKER_TAG', defaultValue: 'chameleoncloud-ocata',
           description: 'Tag to apply to built docker image')
  }

  triggers {
    upstream(upstreamProjects: 'base-kolla', threshold: hudson.model.Result.SUCCESS)

    GenericTrigger(
      genericVariables: [
        [key: 'ref', value: '$.ref'],
        [key: 'changed_files', value: '$.commits[*].["modified","added","removed"][*]']
      ],
      causeString: 'Triggered on $ref',
      token: JOB_NAME,
      printContributedVariables: true,
      regexpFilterText: '$ref $changed_files',
      regexpFilterExpression: 'refs/heads/master .*ironic/'
    )
  }

  environment {
    // Necessary so that `docker login` credentials are not put in shared location
    HOME = "${env.WORKSPACE}"
    DOCKER_REGISTRY = 'docker.chameleoncloud.org'
    DOCKER_REGISTRY_CREDS = credentials('kolla-docker-registry-creds')
  }

  stages {
    stage('docker-setup') {
      steps {
        sh 'docker login --username=$DOCKER_REGISTRY_CREDS_USR --password=$DOCKER_REGISTRY_CREDS_PSW $DOCKER_REGISTRY'
      }
    }

    stage('build-and-publish') {
      environment {
        KOLLA_BUILD_PROFILE = 'ironic'
        KOLLA_PUSH = 'yes'
      }

      steps {
        sh 'make clean'
        sh 'make build'
      }
    }
  }

  post {
    always {
      sh 'docker logout $DOCKER_REGISTRY'
    }
  }
}
