pipeline {
  agent any

  parameters{
    string(name: 'DOCKER_TAG', defaultValue: 'train',
           description: 'Tag to apply to built docker image')
    string(name: 'IRONIC_JOB_NAME', defaultValue: 'ironic/chameleoncloud%2Ftrain',
           description: 'Jenkins job name for ironic')
  }

  triggers {
    upstream(upstreamProjects: "base-kolla/${env.BRANCH_NAME},${params.IRONIC_JOB_NAME}",
             threshold: hudson.model.Result.SUCCESS)
  }

  environment {
    // Necessary so that `docker login` credentials are not put in shared location
    HOME = "${env.WORKSPACE}"
    DOCKER_REGISTRY = 'docker.chameleoncloud.org'
    DOCKER_REGISTRY_CREDS = credentials('kolla-docker-registry-creds')
  }

  stages {
    stage('docker-setup') {
      steps {
        sh 'docker login --username=$DOCKER_REGISTRY_CREDS_USR --password=$DOCKER_REGISTRY_CREDS_PSW $DOCKER_REGISTRY'
      }
    }

    stage('build-and-publish') {
      environment {
        KOLLA_BUILD_PROFILE = 'ironic'
        KOLLA_PUSH = 'yes'
      }

      steps {
        sh 'make clean'
        withPythonEnv('python3') {
          sh 'make build'
        }
      }
    }
  }

  post {
    failure {
      slackSend(
        channel: "#notifications",
        message: "*Build* of *ironic* (${env.DOCKER_TAG}) failed. <${env.RUN_DISPLAY_URL}|View build log>",
        color: "danger"
      )
    }

    success {
      slackSend(
        channel: "#notifications",
        message: "*Build* of *ironic* (${env.DOCKER_TAG}) completed successfuly. <${env.RUN_DISPLAY_URL}|View build log>",
        color: "good"
      )
      build job: 'kolla-ansible-deploy', wait: false, parameters: [
        string(name: 'KOLLA_SERVICE_NAME', value: 'ironic'),
        string(name: 'JENKINS_AGENT_LABEL', value: 'ansible-uc-dev')
      ]
    }
  }
}
