pipeline {
  agent any

  parameters {
    string(name: 'DOCKER_TAG', defaultValue: 'train',
           description: 'Tag to apply to built docker image')
  }

  triggers {
    // Force a rebuild every month to keep things sort of fresh
    cron('@monthly')
  }

  environment {
    // Necessary so that `docker login` credentials are not put in shared location
    HOME = "${env.WORKSPACE}"
    DOCKER_REGISTRY = 'docker.chameleoncloud.org'
    DOCKER_REGISTRY_CREDS = credentials('kolla-docker-registry-creds')
  }

  stages {
    stage('build-and-publish') {
      steps {
        sh 'docker login --username=$DOCKER_REGISTRY_CREDS_USR --password=$DOCKER_REGISTRY_CREDS_PSW $DOCKER_REGISTRY'
        withPythonEnv('python3') {
          sh './run.sh python build.py --config-set base --push --no-use-cache'
        }
      }
    }
  }

  post {
    always {
      sh 'docker logout $DOCKER_REGISTRY'
    }

    failure {
      slackSend(
        channel: "#notifications",
        message: "*Build* of *base* (${env.DOCKER_TAG}) failed. <${env.RUN_DISPLAY_URL}|View build log>",
        color: "danger"
      )
    }

    success {
      slackSend(
        channel: "#notifications",
        message: "*Build* of *base* (${env.DOCKER_TAG}) completed successfuly. <${env.RUN_DISPLAY_URL}|View build log>",
        color: "good"
      )
    }
  }
}
