#!/bin/bash
#
# prebuild-sources.sh
#
# Convert every non-`url` source declared in kolla-build.conf into a
# *deterministic* local archive staged under sources/, and emit a generated
# config (sources.generated.conf) that points kolla at those archives via
# `type = local`.
#
# Why: kolla's built-in `type = git` handling clones the repo and tars the
# working tree on every build. The resulting archive is non-deterministic
# because (a) git sets checked-out file mtimes to "now" and (b) the .git
# directory (pack files, FETCH_HEAD, ...) varies run to run. Identical source
# content therefore produces different archive bytes, which busts the Docker
# `ADD` layer cache for that image and everything below it.
#
# Building a PBR sdist on the host (where .git is available) instead:
#   * bakes the version into PKG-INFO, so .git is not needed in the container
#     (this also handles images with multiple sources at independent versions,
#      e.g. neutron-base + its networking-* plugins), and
#   * with SOURCE_DATE_EPOCH set to the commit time, produces byte-reproducible
#     output -> stable ADD layer digest -> cache hit on a no-change rebuild.
#
# The script is itself idempotent: it records the resolved source SHA per
# section and skips rebuilding an archive whose source has not changed.

set -euo pipefail

# Run from the repo root (parent of tools/).
cd "$(dirname "$0")/.."
REPO_ROOT="$(pwd)"

PYTHON="${PYTHON:-${REPO_ROOT}/.venv/bin/python}"
SRC_CONF="${SRC_CONF:-kolla-build.conf}"
OUT_CONF="${OUT_CONF:-sources.generated.conf}"
SOURCES_DIR="${SOURCES_DIR:-sources}"
CACHE_DIR="${CACHE_DIR:-.cache/repos}"
LOG_DIR="${LOG_DIR:-logs}"

mkdir -p "${SOURCES_DIR}" "${CACHE_DIR}" "${LOG_DIR}"
# Resolve to absolute paths so archive locations are unambiguous regardless of
# the (relative or absolute) values passed in, and so the generated config
# points kolla at absolute locations.
SOURCES_DIR="$(cd "${SOURCES_DIR}" && pwd)"
CACHE_DIR="$(cd "${CACHE_DIR}" && pwd)"
LOG_DIR="$(cd "${LOG_DIR}" && pwd)"

# Enumerate the source sections we need to stage: any section that declares
# `type = git` or `type = local`. Emit one TSV row per section:
#   <section>\t<type>\t<location>\t<reference>
read_sections() {
    "${PYTHON}" - "${SRC_CONF}" <<'PY'
import configparser
import sys

cp = configparser.RawConfigParser()
cp.read(sys.argv[1])
for section in cp.sections():
    if not cp.has_option(section, "type"):
        continue
    stype = cp.get(section, "type")
    if stype not in ("git", "local"):
        continue
    location = cp.get(section, "location", fallback="")
    reference = cp.get(section, "reference", fallback="")
    print("\t".join((section, stype, location, reference)))
PY
}

# Start the generated config fresh.
{
    echo "# Generated by tools/prebuild-sources.sh -- do not edit."
    echo "# Each section below overrides the matching git/local source in"
    echo "# ${SRC_CONF} with a deterministic, pre-staged local archive."
} > "${OUT_CONF}"

emit_section() {
    local section="$1" archive="$2"
    {
        echo ""
        echo "[${section}]"
        echo "type = local"
        echo "location = ${archive}"
    } >> "${OUT_CONF}"
}

# Repack a directory into a byte-reproducible, uncompressed tar, following
# https://reproducible-builds.org/docs/archives/ :
#   canonical_tar <parent_dir> <top_entry> <out.tar> <epoch>
# We force a single mtime, sort entries, and zero the owner. We deviate from
# the doc's reference command in two deliberate, more-conservative ways:
#   * --format=gnu instead of the PAX --pax-option=delete=atime,ctime dance.
#     GNU format carries no atime/ctime/sub-second PAX records (so nothing to
#     strip) and, unlike ustar, has no 100-char path limit -- important for
#     OpenStack's deep package trees.
#   * uncompressed output instead of `gzip -n`. -n only fixes the gzip header
#     timestamp; the compressed stream can still vary across zlib versions.
#     Staying uncompressed removes that cross-host variable entirely (Docker
#     ADD and kolla both read uncompressed tar fine).
# We set mtime explicitly rather than trusting SOURCE_DATE_EPOCH: the spec
# notes "not all upstream tools" honor it, and setuptools' sdist is one that
# does not clamp member mtimes -- verified here, hence this repack.
canonical_tar() {
    local parent="$1" top="$2" out="$3" epoch="$4"
    tar --sort=name --format=gnu --mtime="@${epoch}" \
        --owner=0 --group=0 --numeric-owner \
        -C "${parent}" -cf "${out}" "${top}"
}

# Build a reproducible PBR sdist for a git source.
build_git_sdist() {
    local section="$1" url="$2" ref="$3"
    local clone="${CACHE_DIR}/${section}"
    local archive="${SOURCES_DIR}/${section}.tar"
    local stamp="${SOURCES_DIR}/${section}.sha"
    local log="${LOG_DIR}/${section}.log"

    # Verbose git + sdist output goes to a per-source log; the console only gets
    # the one-line status below. Each run starts the log fresh.
    echo "=== ${section}: fetch + sdist build ($(date -u +%FT%TZ)) ===" > "${log}"

    {
        if [ -d "${clone}/.git" ]; then
            git -C "${clone}" remote set-url origin "${url}"
            git -C "${clone}" fetch --tags --force --prune origin "${ref}"
        else
            rm -rf "${clone}"
            git clone "${url}" "${clone}"
            git -C "${clone}" fetch --tags --force origin "${ref}"
        fi
        # Detach onto the fetched ref (works for branch, tag, or sha) and scrub
        # any leftovers from a previous sdist build so PBR regenerates cleanly.
        git -C "${clone}" checkout --force --detach FETCH_HEAD
        git -C "${clone}" reset --hard
        git -C "${clone}" clean -ffdx
    } >> "${log}" 2>&1

    local sha epoch
    sha="$(git -C "${clone}" rev-parse HEAD)"
    epoch="$(git -C "${clone}" log -1 --format=%ct)"

    if [ -f "${archive}" ] && [ -f "${stamp}" ] && \
       [ "$(cat "${stamp}")" = "${sha}" ]; then
        echo "  ${section}: unchanged (${sha:0:12}), reusing ${archive}"
        emit_section "${section}" "${archive}"
        return
    fi

    echo "  ${section}: building sdist @ ${sha:0:12} -> log ${log#"${REPO_ROOT}"/}"
    {
        rm -rf "${clone}/dist"
        # Build the sdist so PBR bakes the version, PKG-INFO, AUTHORS and
        # ChangeLog in (no .git needed in the container). SOURCE_DATE_EPOCH
        # makes the generated content deterministic; member mtimes are
        # normalized in the canonical repack below.
        ( cd "${clone}" && SOURCE_DATE_EPOCH="${epoch}" \
            "${PYTHON}" -m build --sdist --no-isolation --outdir dist )
    } >> "${log}" 2>&1

    # PBR/setuptools emits exactly one sdist tarball into dist/. Re-pack it into
    # a canonical tar so the bytes are reproducible regardless of build host.
    local built unpack top
    built="$(ls "${clone}"/dist/*.tar.gz)"
    unpack="$(mktemp -d)"
    tar -xf "${built}" -C "${unpack}"
    top="$(ls "${unpack}")"
    canonical_tar "${unpack}" "${top}" "${archive}" "${epoch}"
    rm -rf "${unpack}"
    echo "${sha}" > "${stamp}"
    emit_section "${section}" "${archive}"
}

# Canonical, deterministic tar of a local directory (e.g. blazar additions).
# Output is uncompressed (.tar) to sidestep gzip header non-determinism;
# kolla auto-detects compression when it reads the archive back.
build_local_tar() {
    local section="$1" location="$2"
    local archive="${SOURCES_DIR}/${section}.tar"
    local log="${LOG_DIR}/${section}.log"

    echo "=== ${section}: canonical tar ($(date -u +%FT%TZ)) ===" > "${log}"

    if [ ! -d "${location}" ]; then
        # A local *file* source: copy verbatim, it is already a fixed artifact.
        archive="${SOURCES_DIR}/${section}.$(basename "${location}")"
        echo "  ${section}: copying local file ${location} -> ${archive}" | tee -a "${log}"
        cp -f "${location}" "${archive}"
        emit_section "${section}" "${archive}"
        return
    fi

    # Pin mtimes to the last commit that touched this path for stability.
    local epoch
    epoch="$(git log -1 --format=%ct -- "${location}" 2>/dev/null || echo 0)"
    echo "  ${section}: canonical tar of ${location} (mtime=@${epoch}) -> log ${log#"${REPO_ROOT}"/}"
    canonical_tar "$(dirname "${location}")" "$(basename "${location}")" \
        "${archive}" "${epoch}" >> "${log}" 2>&1
    emit_section "${section}" "${archive}"
}

echo "Staging deterministic sources into ${SOURCES_DIR}/ ..."
while IFS=$'\t' read -r section stype location reference; do
    [ -n "${section}" ] || continue
    case "${stype}" in
        git)   build_git_sdist "${section}" "${location}" "${reference}" ;;
        local) build_local_tar "${section}" "${location}" ;;
    esac
done < <(read_sections)

echo "Wrote ${OUT_CONF}"
