pipeline {
  agent any

  parameters {
    string(name: 'KEYSTONE_JOB_NAME', defaultValue: 'keystone/chameleoncloud%2Frocky',
           description: 'Jenkins job name for keystone')
  }

  triggers {
    upstream(upstreamProjects: "base-kolla/${env.BRANCH_NAME},${params.KEYSTONE_JOB_NAME}",
             threshold: hudson.model.Result.SUCCESS)
  }

  environment {
    // Necessary so that `docker login` credentials are not put in shared location
    HOME = "${env.WORKSPACE}"
    DOCKER_REGISTRY = 'docker.chameleoncloud.org'
    DOCKER_REGISTRY_CREDS = credentials('kolla-docker-registry-creds')
  }

  stages {
    stage('docker-setup') {
      steps {
        sh 'docker login --username=$DOCKER_REGISTRY_CREDS_USR --password=$DOCKER_REGISTRY_CREDS_PSW $DOCKER_REGISTRY'
      }
    }

    stage('build-and-publish') {
      environment {
        KOLLA_BUILD_PROFILE = 'keystone'
        KOLLA_PUSH = 'yes'
      }

      steps {
        copyArtifacts(projectName: "${params.KEYSTONE_JOB_NAME}",
                      target: "${env.WORKSPACE}/sources")
        sh 'make clean'
        sh 'make build-with-locals'
      }
    }
  }

  post {
    always {
      sh 'docker logout $DOCKER_REGISTRY'
    }

    success {
      build job: 'kolla-ansible-deploy', wait: false, parameters: [
        string(name: 'KOLLA_SERVICE_NAME', value: 'keystone'),
        string(name: 'JENKINS_AGENT_LABEL', value: 'ansible-uc-dev')
      ]
    }
  }
}
