pipeline {
  agent any

  parameters {
    string(name: 'DONI_JOB_NAME', defaultValue: 'doni/main',
           description: 'Jenkins job name for doni')
    string(name: 'DOCKER_TAG', defaultValue: 'train',
           description: 'Tag to apply to built docker image (defaults to value defined in source repo)')
    booleanParam(name: 'KOLLA_USE_CACHE', defaultValue: true,
                 description: 'Leverage already-built artifacts for faster processing')
  }

  triggers {
    upstream(upstreamProjects: "base-kolla/${env.BRANCH_NAME},${params.DONI_JOB_NAME}",
             threshold: hudson.model.Result.SUCCESS)
  }

  environment {
    // Necessary so that `docker login` credentials are not put in shared location
    HOME = "${env.WORKSPACE}"
    DOCKER_REGISTRY = 'docker.chameleoncloud.org'
    DOCKER_REGISTRY_CREDS = credentials('kolla-docker-registry-creds')
    KOLLA_BUILD_PROFILE = 'doni'
    KOLLA_PUSH = 'yes'
    KOLLA_LOCAL_SOURCES = 'yes'
    KOLLA_USE_CACHE = "${boolToString(params.KOLLA_USE_CACHE)}"
  }

  stages {
    stage('docker-setup') {
      steps {
        sh 'docker login --username=$DOCKER_REGISTRY_CREDS_USR --password=$DOCKER_REGISTRY_CREDS_PSW $DOCKER_REGISTRY'
      }
    }

    stage('build-and-publish') {
      steps {
        copyArtifacts(projectName: "${params.DONI_JOB_NAME}",
                      target: "${env.WORKSPACE}/sources")
        sh 'rm -rf build'
        withPythonEnv('python3') {
          sh './run.sh python build.py --push --use-cache'
        }
      }
    }
  }

  post {
    always {
      sh 'docker logout $DOCKER_REGISTRY'
    }

    failure {
      slackSend(
        channel: "#notifications",
        message: "*Build* of *doni* (${env.DOCKER_TAG}) failed. <${env.RUN_DISPLAY_URL}|View build log>",
        color: "danger"
      )
    }

    success {
      slackSend(
        channel: "#notifications",
        message: "*Build* of *doni* (${env.DOCKER_TAG}) completed successfuly. <${env.RUN_DISPLAY_URL}|View build log>",
        color: "good"
      )
      build job: 'kolla-ansible-deploy', wait: false, parameters: [
        string(name: 'KOLLA_SERVICE_NAME', value: 'doni'),
        string(name: 'JENKINS_AGENT_LABEL', value: 'ansible-uc-dev')
      ]
    }
  }
}

def boolToString(Boolean value) {
  return value ? "yes" : "no"
}
