pipeline {
  agent any

  parameters {
    string(name: 'BLAZAR_JOB_NAME', defaultValue: 'blazar/chameleoncloud%2Frocky',
           description: 'Jenkins job name for blazar')
    string(name: 'DOCKER_TAG', defaultValue: 'chameleoncloud-rocky',
           description: 'Tag to apply to built docker image')
  }

  triggers {
    upstream(upstreamProjects: "base-kolla/${env.BRANCH_NAME},${params.BLAZAR_JOB_NAME}",
             threshold: hudson.model.Result.SUCCESS)
  }

  environment {
    // Necessary so that `docker login` credentials are not put in shared location
    HOME = "${env.WORKSPACE}"
    DOCKER_REGISTRY = 'docker.chameleoncloud.org'
    DOCKER_REGISTRY_CREDS = credentials('kolla-docker-registry-creds')
  }

  stages {
    stage('docker-setup') {
      steps {
        sh 'docker login --username=$DOCKER_REGISTRY_CREDS_USR --password=$DOCKER_REGISTRY_CREDS_PSW $DOCKER_REGISTRY'
      }
    }

    stage('build-and-publish') {
      environment {
        KOLLA_BUILD_PROFILE = 'blazar'
        KOLLA_PUSH = 'yes'
      }

      steps {
        copyArtifacts(projectName: "${params.BLAZAR_JOB_NAME}",
                      target: "${env.WORKSPACE}/sources")
        sh "make clean"
        sh "make build-with-locals"
      }
    }
  }

  post {
    always {
      sh 'docker logout $DOCKER_REGISTRY'
    }

    success {
      build job: 'kolla-ansible-deploy', wait: false, parameters: [
        string(name: 'KOLLA_SERVICE_NAME', value: 'blazar'),
        string(name: 'JENKINS_AGENT_LABEL', value: 'ansible-uc-dev')
      ]
    }
  }

}
