name: ci

on:
  push:
    branches:
      - master
      - staging
  workflow_dispatch:
    inputs:
      kolla_build_profile:
        description: "Kolla Profile to build"
        required: true
        default: base

env:
  DOCKER_REGISTRY: docker.chameleoncloud.org
  KOLLA_NAMESPACE: kolla-dev
  KOLLA_BUILD_PROFILE: ${{ github.event.inputs.kolla_build_profile }} 

jobs:
  buildx:
    environment: Chameleon CI
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        config_set:
          - aarch64_debian
          - aarch64_ubuntu
          - x86_centos
          - x86_ubuntu
    steps:
      - name: Set env to staging
        if: endsWith(github.ref, '/staging')
        run: echo "SHOULD_PUSH=1" >> $GITHUB_ENV
      - name: Set env to production
        if: endsWith(github.ref, '/master')
        run: |
          echo "KOLLA_NAMESPACE=kolla" >> $GITHUB_ENV
          echo "SHOULD_PUSH=1" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Cache python deps
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
      - name: Login to Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ secrets.CC_REGISTRY_USERNAME }}
          password: ${{ secrets.CC_REGISTRY_PASSWORD }}
      - name: Inspect builder
        run: |
          echo "Name:      ${{ steps.buildx.outputs.name }}"
          echo "Endpoint:  ${{ steps.buildx.outputs.endpoint }}"
          echo "Status:    ${{ steps.buildx.outputs.status }}"
          echo "Flags:     ${{ steps.buildx.outputs.flags }}"
          echo "Platforms: ${{ steps.buildx.outputs.platforms }}"
      - name: Run Kolla Build
        run: |
          ./run.sh python build.py --config-set ${{ matrix.config_set }} \
            --profile ${{ env.KOLLA_BUILD_PROFILE }} \
            ${{ fromJSON('["--no-push", "--push"]')[env.SHOULD_PUSH] }}
      - name: List Build Images
        run: docker image ls
