name: ci

on:
  push:
  workflow_dispatch:
    inputs:
      kolla_profile:
        description: "Specific service to build"
        required: false
jobs:
  buildx:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [aarch64]
        base_os: [ubuntu]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
      - name: Inspect builder
        run: |
          echo "Name:      ${{ steps.buildx.outputs.name }}"
          echo "Endpoint:  ${{ steps.buildx.outputs.endpoint }}"
          echo "Status:    ${{ steps.buildx.outputs.status }}"
          echo "Flags:     ${{ steps.buildx.outputs.flags }}"
          echo "Platforms: ${{ steps.buildx.outputs.platforms }}"
      - name: Run Kolla Build
        env:
          KOLLA_BUILD_PROFILE: ${{ github.event.inputs.kolla_profile }}
          KOLLA_USE_CACHE: no
          KOLLA_BASE_ARCH: ${{ matrix.arch }}
          KOLLA_BASE: ${{ matrix.base_os }}
        run: make build 
