name: build-containers

on:
  workflow_dispatch:
    inputs:
      kolla_build_profile:
        description: "Kolla profile to invoke (e.g., 'ironic')"
        type: string
      kolla_build_pattern:
        description: "Kolla image build pattern (e.g., '^ironic-')"
        type: string
      push:
        type: choice
        description: "Push images to registry? (true/false)"
        required: true
        default: 'false'
        options:
          - 'true'
          - 'false'
      tag:
        type: string
        description: "Docker tag for built images, overrides default of git-sha"
env:
  REGISTRY: ghcr.io

jobs:
  build-containers:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: ./install.sh
      - name: Login to Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Kolla Build
        env:
          BUILD_PROFILE: ${{ inputs.kolla_build_profile }}
          BUILD_PATTERN: ${{ inputs.kolla_build_pattern }}
          BUILD_TAG: ${{ inputs.tag }}
        run: |
          ./run.sh \
          --work-dir $RUNNER_TEMP \
          --threads $(nproc)
